version: "3.3"
services:
  database:
    image: mongo:6.0.4
    command: --replSet rs0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: uecevents
    volumes:
      - ./volumes:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
